version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  api:
    build: ./api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
      - public:/app/public
      - tmp:/app/tmp
      - log:/app/log
    tty: true
    stdin_open: true
  front:
    build: ./front
    volumes:
      - ./front/:/app
    tty: true
    stdin_open: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.10
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - api
    command: /bin/sh -c "yarn install && expo start"
volumes:
  mysql_data:
  bundle:
  public:
  tmp:
  log:
